Removed all builtin, it causes problems on some versions of bash

diff --git a/sh/bash/bashrc b/sh/bash/bashrc
--- a/sh/bash/bashrc
+++ b/sh/bash/bashrc
@@ -3,21 +3,21 @@ shopt -s checkwinsize
 
 # Loading completions from the appropriate directory
 for compl in `find $DIRCONFIG/sh/bash/completions -maxdepth 1 -iname "[^.]*.bash-completions" -type f`; do
-  builtin source $compl 2>/dev/null || builtin echo "Failed to load completion $compl" >&2
+  source $compl 2>/dev/null || echo "Failed to load completion $compl" >&2
 done
 
 # Ensuring the default theme is loaded
-builtin source $DIRCONFIG/sh/bash/themes/default_theme.bash_theme
+source $DIRCONFIG/sh/bash/themes/default_theme.bash_theme
 
 # Load the customization options
 for custom in `find $DIRCONFIG/sh/bash/custom -maxdepth 1 -iname "[^.]*.bash" -type f`; do
-  builtin source $custom 2>/dev/null || builtin echo "Failed to load custom $custom" >&2
+  source $custom 2>/dev/null || echo "Failed to load custom $custom" >&2
 done
 
 # https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
-if ! builtin test -z ${BASH_THEME+x}; then
-  builtin source $DIRCONFIG/sh/bash/themes/"$BASH_THEME".bash_theme 2>/dev/null || builtin echo "Failed to load theme: $BASH_THEME" >&2
+if ! test -z ${BASH_THEME+x}; then
+  source $DIRCONFIG/sh/bash/themes/"$BASH_THEME".bash_theme 2>/dev/null || echo "Failed to load theme: $BASH_THEME" >&2
 fi
 
 PROMPT_COMMAND='make_bash_prompt'
-builtin export PROMPT_COMMAND
+export PROMPT_COMMAND
diff --git a/sh/profile b/sh/profile
--- a/sh/profile
+++ b/sh/profile
@@ -1,59 +1,59 @@
 # https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
-if builtin test -z ${DIRCONFIG+x}; then
+if test -z ${DIRCONFIG+x}; then
   DIRCONFIG=$HOME/.config
-  builtin export DIRCONFIG
+  export DIRCONFIG
 fi
-builtin test -d $DIRCONFIG || mkdir -p $DIRCONFIG
+test -d $DIRCONFIG || mkdir -p $DIRCONFIG
 
 # Loading the basic file
-builtin source $DIRCONFIG/sh/common/basic.sh
+source $DIRCONFIG/sh/common/basic.sh
 
 # Loading the optional modules
 for option in `find $DIRCONFIG/sh/options -maxdepth 1 -iname "[^.]*[^.md]" -type f`; do
   _mod=$DIRCONFIG/sh/common/modules/$(basename $option).sh
-  builtin source $_mod 2>/dev/null || builtin echo "Failed to load module $_mod" >&2
+  source $_mod 2>/dev/null || echo "Failed to load module $_mod" >&2
 done
-builtin unset _mod
+unset _mod
 
 # If the user has a personal bin directory, use it as first element in the path
 # Else, avoid cluttering the path
-if builtin test -d $HOME/bin; then
+if test -d $HOME/bin; then
   case :$PATH: in
     *:$HOME/bin:*)
       ;;
     *)
       PATH=$HOME/bin:$PATH
-      builtin export PATH
+      export PATH
       ;;
   esac
 fi
-if builtin test -d $HOME/.bin; then
+if test -d $HOME/.bin; then
   case :$PATH: in
     *:$HOME/.bin:*)
       ;;
     *)
       PATH=$HOME/.bin:$PATH
-      builtin export PATH
+      export PATH
       ;;
   esac
 fi
-if builtin test -d $DIRCONFIG/sh/bin; then
+if test -d $DIRCONFIG/sh/bin; then
   case :$PATH: in
     *:$DIRCONFIG/sh/bin:*)
       ;;
     *)
       PATH=$DIRCONFIG/sh/bin:$PATH
-      builtin export PATH
+      export PATH
       ;;
   esac
 fi
 
 # Shell specific file
 shell_rc=""
-if ! builtin test -z ${ZSH_NAME+x}; then
+if ! test -z ${ZSH_NAME+x}; then
   shell_rc=$DIRCONFIG/sh/zsh/zshrc
-elif ! builtin test -z ${BASH+x}; then
+elif ! test -z ${BASH+x}; then
   shell_rc=$DIRCONFIG/sh/bash/bashrc
 fi
-builtin source $shell_rc 2>/dev/null || builtin echo "Could not load rc file: $shell_rc" >&2
-builtin unset shell_rc
+source $shell_rc 2>/dev/null || echo "Could not load rc file: $shell_rc" >&2
+unset shell_rc
